version: "3.7"
 
services:
  node-ts-otimizado:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: example-web-server
    volumes:
      - ./src:/app/src
    ports:
      - "3000:8080"
      - "8181:8181"
    command: npm run dev