version: "3.7"
 
services:
  colab-context:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: colab-context
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    command: npm run dev